# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for dist2src worker
  hosts: all
  tasks:
    - name: Install all RPMs needed to install & run dist2src worker
      dnf:
        name:
          - python3-prometheus_client
    - name: Install pip deps
      pip:
        name:
          - sentry-sdk
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip3 check
